#!/usr/bin/env bash
# Sets up the environmental variables used for the project
HBNB_ENV=test
HBNB_MYSQL_USER=hbnb_test
HBNB_MYSQL_PWD=hbnb_test_pwd
HBNB_MYSQL_HOST=localhost
HBNB_MYSQL_DB=hbnb_test_db
HBNB_TYPE_STORAGE=file
